# Generated by Django 5.0.3 on 2024-05-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.CharField()),
                ('max_weight', models.CharField()),
                ('self_weight', models.CharField()),
                ('platform_size', models.CharField()),
                ('axle_weight', models.CharField()),
                ('availability', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/katalog/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.CharField()),
                ('image_news', models.ImageField(upload_to='images/news/')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('phone', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('pricep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='katalog.katalog')),
            ],
        ),
    ]
